### ISSUE TITLE
Make 'npm test' actually do something (that returns 0 error code)

### ISSUE THREAD

**Issue by tkissing** [konobi/kwalitee#10]
It's still the default "there are no tests"

**Comment by konobi** [comment]
Yeah, that comes from npm init... or if it's not in the package.json, it comes from within npm as a default. It should always be in the package.json. Since the string can be totally freeform, not sure how/what to check.

**Comment by tkissing** [comment]
At the very least you could verify that it's there and not the default.
Could also check for common test commands ("karma start", "grunt karma", "tape 'tests/*_/_.tap.js'" etc)

**Comment by konobi** [comment]
I suppose checking for '&&' might work. Defaults can change over time, as can common test commands, so not as big a fan of that.

**Comment by tkissing** [comment]
I doubt the "&& exit 1" part of the default will change anytime soon, so that should be safe to check for.
