### ISSUE TITLE
Name folder containing tests 'tests' or 'test', not just 't'

### ISSUE THREAD

**Issue by tkissing** [konobi/kwalitee#9]
Yes, short paths are nice, but readable folder names that clearly communicate what's inside are nicer.

**Comment by konobi** [comment]
"t" is a historical porpoises standard. We should pick either "test" or "tests" as the standard.

**Comment by tkissing** [comment]
I am using "tests", but "test" is very common in the Java/Maven world, "spec" is used a lot with Ruby - there are probably others. Whatever you pick for this project itself is somewhat up to your personal taste I guess. For measuring other modules I'd say either is acceptable, because all those folder names are common and understood.

**Comment by konobi** [comment]
"t" is also common in the perl world. But... I think we'll go with "test", as it seems to be the most commonplace.

**Comment by tkissing** [comment]
Yeah, but perl is write-only code ;)
